version: '3'

services:
  postgres:
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres:11.3-alpine
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data
  
  keycloak:
    command: -b 0.0.0.0 -bmanagement 0.0.0.0 -c standalone-ha.xml
    image: jboss/keycloak:6.0.1
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      DB_ADDR: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_VENDOR: postgres
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_USER: admin
      PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      - ./keycloak/discovery:/opt/jboss/tools/cli/jgroups/discovery
      - ./keycloak/startup-scripts:/opt/jboss/startup-scripts/
      - ./keycloak/themes/stone:/opt/jboss/keycloak/themes/stone
      - keycloak-discovery:/var/lib/jgroups

volumes:
  keycloak-discovery:
  keycloak-postgres: